#!/usr/bin/env node
/**
 * Copies the SAME game files the website serves into app/www/ so the iOS
 * wrapper always ships whatever's currently at the repo root.
 * Never hand-edit anything inside app/www — it's regenerated by this script
 * (run automatically by `npm run sync`, or manually with `npm run build:www`).
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..'); // repo root (nasty-game/)
const WWW = path.resolve(__dirname, '..', 'www'); // app/www

const FILES = ['index.html', 'manifest.json', 'icon.png'];

fs.rmSync(WWW, { recursive: true, force: true });
fs.mkdirSync(WWW, { recursive: true });

for (const f of FILES) {
  const src = path.join(ROOT, f);
  const dst = path.join(WWW, f);
  fs.copyFileSync(src, dst);
  console.log(`copied ${f} -> app/www/${f}`);
}

console.log('app/www is up to date with repo root.');
